# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 06:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('plot', models.TextField(max_length=1000, verbose_name='Plot')),
                ('poster', models.ImageField(upload_to='movies/covers/')),
                ('runtime', models.IntegerField(default=0, verbose_name='Runtime')),
                ('imdbID', models.IntegerField(default=0, verbose_name='Imdb')),
                ('imdbRating', models.FloatField(default=0.0, verbose_name='Imdb Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
