# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160218_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='horizontal_poster',
            field=models.ImageField(blank=True, upload_to='movies/covers/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Original Title'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Trailer'),
        ),
    ]
