# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160303_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
    ]
