# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 3, 6, 30, 53, 692259, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 3, 6, 31, 0, 346654, tzinfo=utc), verbose_name='Updated at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
