# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_auto_20160303_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='function',
            name='time',
        ),
        migrations.AddField(
            model_name='show',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.Function'),
        ),
    ]
