# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid

def generate_uuid(apps, schema_editor):
    Function = apps.get_model('cinemas', 'Function')
    for function in Function.objects.all().iterator():
        function.uuid = uuid.uuid4()

        function.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_auto_20160306_1942'),
    ]

    operations = [
        migrations.RunPython(
            generate_uuid,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='function',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
            preserve_default=True,
        ),
    ]
