# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_auto_20160309_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='published_from',
            field=models.DateField(default=datetime.datetime(2016, 3, 11, 4, 53, 12, 279977, tzinfo=utc), verbose_name='Published from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtimes',
            name='published_until',
            field=models.DateField(default=datetime.datetime(2016, 3, 11, 4, 53, 20, 231514, tzinfo=utc), verbose_name='Published until'),
            preserve_default=False,
        ),
    ]
