# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_auto_20160310_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Phone'),
        ),
    ]
