# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_cinema_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(blank=True, choices=[('santiago-de-cali', 'Santiago de Cali'), ('medellin', 'Medell\xedn')], max_length=50, verbose_name='City'),
        ),
    ]
