# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0012_auto_20160311_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_3D', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.Function')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='auditorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.Auditorium'),
        ),
        migrations.AddField(
            model_name='functiontype',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.Show'),
        ),
        migrations.AddField(
            model_name='function',
            name='showtimes',
            field=models.ManyToManyField(through='cinemas.FunctionType', to='cinemas.Show'),
        ),
    ]
