# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0013_auto_20160311_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functiontype',
            name='show',
        ),
        migrations.RemoveField(
            model_name='show',
            name='auditorium',
        ),
        migrations.AddField(
            model_name='functiontype',
            name='auditorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.Auditorium'),
        ),
        migrations.AddField(
            model_name='show',
            name='function_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.FunctionType'),
        ),
        migrations.AlterField(
            model_name='function',
            name='showtimes',
            field=models.ManyToManyField(through='cinemas.FunctionType', to='cinemas.Auditorium'),
        ),
    ]
