# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def generate_uuid(apps, schema_editor):
    Auditorium = apps.get_model('cinemas', 'Auditorium')
    for auditorium in Auditorium.objects.all().iterator():
        auditorium.uuid = uuid.uuid4()

        auditorium.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0014_auto_20160311_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, unique=False, null=True),
        ),
        migrations.RunPython(
            generate_uuid,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
            preserve_default=True,
        ),
    ]
