# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0015_auditorium_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='booking_url',
            field=models.URLField(blank=True, verbose_name='Booking URL'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='functiontype',
            name='is_3D',
            field=models.BooleanField(default=False, verbose_name='Is 3D'),
        ),
    ]
