# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(max_length=55, verbose_name='Imdb'),
        ),
    ]
